# 4) Working with Tabular Data

## Reading in Tabular Data


In [4]:
import numpy
help(numpy.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [5]:
import os

distance_file = os.path.join('data', 'distance_data_headers.csv')

distances = numpy.genfromtxt(fname=distance_file, delimiter=',', dtype='unicode')
print(distances)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


Doing the same but using pandas instead of numpy

In [6]:
import pandas as pd
distances_pd=pd.read_csv(distance_file)
distances_pd

Frame  THR4_ATP  THR4_ASP  TYR6_ATP  TYR6_ASP
0         1    8.9542    5.8024   11.5478    9.9557
1         2    8.6181    6.0942   13.9594   11.6945
2         3    9.0066    6.0637   13.0924   11.3043
3         4    9.2002    6.0227   14.5282   10.1763
4         5    9.1294    5.9365   13.5321   10.6279
...     ...       ...       ...       ...       ...
9995   9996    8.5083    7.7587    9.1789   10.6715
9996   9997    8.9524    7.4681    9.5132   10.9945
9997   9998    8.6625    7.7306    9.5469   10.3063
9998   9999    9.2456    7.8886    9.8151   10.7564
9999  10000    8.8135    7.9170    9.9517   10.7848

[10000 rows x 5 columns]

## Manipulating Tabular Data

In [8]:
headers = distances[0]
print(headers)

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']


Take a slice of the data that is just the numerical values. To be uniform for later activities, call this slice data.

In [9]:
data=distances[1:]
print(data)

[['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ['3' '9.0066' '6.0637' '13.0924' '11.3043']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [10]:
data = data.astype(float)
print(data)

[[1.00000e+00 8.95420e+00 5.80240e+00 1.15478e+01 9.95570e+00]
 [2.00000e+00 8.61810e+00 6.09420e+00 1.39594e+01 1.16945e+01]
 [3.00000e+00 9.00660e+00 6.06370e+00 1.30924e+01 1.13043e+01]
 ...
 [9.99800e+03 8.66250e+00 7.73060e+00 9.54690e+00 1.03063e+01]
 [9.99900e+03 9.24560e+00 7.88860e+00 9.81510e+00 1.07564e+01]
 [1.00000e+04 8.81350e+00 7.91700e+00 9.95170e+00 1.07848e+01]]


In [11]:
print(data[0,1])
print(data[1,0])

8.9542
2.0


In [12]:
small_data=(data[0:10,0:3])
print(small_data)
print('only 6th row')
print(small_data[5,:])
print('columns without indexes')
print(small_data[:,1:])

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]
only 6th row
[6.     9.0462 6.2553]
columns without indexes
[[8.9542 5.8024]
 [8.6181 6.0942]
 [9.0066 6.0637]
 [9.2002 6.0227]
 [9.1294 5.9365]
 [9.0462 6.2553]
 [8.8657 5.9186]
 [9.3256 6.2351]
 [9.4184 6.1993]
 [9.06   6.0478]]


## Analyzing Tabular Data


In [13]:
data_average=numpy.mean(data)
print(data_average)

1008.184506144


In [14]:
thr4_atp = data[:,1]  # Every row, just the THR4_ATP column
avg_thr4_atp = numpy.mean(thr4_atp)
print(avg_thr4_atp)

10.876950930000001


Determine the number of columns in our data set. Save this value as a variable called num_columns.



In [28]:
num_columns=len(data[0,:])
print(num_columns)

5


In [30]:
num_columns=len(data[0,:])

for i in range(1,num_columns):
    column=data[:,i]
    avg_column=numpy.mean(column)
    print(F'{headers[i]}: {avg_column}')

THR4_ATP: 10.876950930000001
THR4_ASP: 7.342344959999999
TYR6_ATP: 11.209791329999998
TYR6_ASP: 10.9934435


### Geometry Analysis Project


In [256]:
import os
import numpy as np

#Opening a file
file_location=os.path.join('data', 'water.xyz')
dataset=numpy.genfromtxt(fname=file_location, dtype='unicode',skip_header=2)

#Separating index from values
headers=dataset[:,0]
data=dataset[:,1:].astype(float)

#determining range of loops
num_atoms=len(headers)
num_columns=len(data[0,:])

#Iterating to repeat the calculation, first we select a row. Once inside the row, we do the same for every column.
#Notice how we substract entire rows, because we know that row1-row0= (x1-x0)+(y1-y0)+(z1-z0). By **2, we apply it to each and then we apply sqrt to all.


for row in range(num_atoms):
    atom_start=headers[row]
    for column in range(num_columns):
        atom_final=headers[column]
        distance=np.sqrt(np.sum((data[column]-data[row])**2))
        print(F'{atom_start} to {atom_final}: {distance}')
       


O to O: 0.0
O to H1: 0.9690005374652793
O to H2: 0.9690003348647513
H1 to O: 0.9690005374652793
H1 to H1: 0.0
H1 to H2: 1.52693633514957
H2 to O: 0.9690003348647513
H2 to H1: 1.52693633514957
H2 to H2: 0.0


#### Solution of exercise:

In [253]:
import numpy
import os

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2,  dtype='unicode')

symbols = xyz_file[:,0]
coordinates = (xyz_file[:,1:])
coordinates = coordinates.astype(float)

num_atoms = len(symbols)


for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        bond_length_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')  

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


### My answer with changes from solution:

In [265]:
import os
import numpy as np

#Opening a file
file_location=os.path.join('data', 'water.xyz')
dataset=numpy.genfromtxt(fname=file_location, dtype='unicode',skip_header=2)

#Separating index from values
headers=dataset[:,0]
data=dataset[:,1:].astype(float)

#determining range of loops
num_atoms=len(headers)

#Iterating to repeat the calculation, first we select a row (ex: Oxygen). Inside every row, we substract 


for row in range(num_atoms):
    for column in range(num_atoms):
        x_distance = data[row,0] - data[column,0]
        y_distance = data[row,1] - data[column,1]
        z_distance = data[row,2] - data[column,2]
        
        distance=np.sqrt(x_distance**2+y_distance**2+z_distance**2)
        print(F'{headers[row]} to {headers[column]}: {distance:.3f}')
    

O to O: 0.000
O to H1: 0.969
O to H2: 0.969
H1 to O: 0.969
H1 to H1: 0.000
H1 to H2: 1.527
H2 to O: 0.969
H2 to H1: 1.527
H2 to H2: 0.000


### Project Extension 1, 2 and 3


In [289]:
import os
import numpy as np

#Opening a file
file_location=os.path.join('data', 'water.xyz')
dataset=numpy.genfromtxt(fname=file_location, dtype='unicode',skip_header=2)

#Separating index from values
headers=dataset[:,0]
data=dataset[:,1:].astype(float)

#determining range of loops
num_atoms=len(headers)

#Iterating to repeat the calculation, first we select a row (ex: Oxygen). Inside every row, we substract 

with open('bond_lengths.txt','w+') as outfile:

    for row in range(num_atoms):
        for column in range(num_atoms):
            if row<column: #We avoid replicate calculations, such as O-H1 and H1-0
                x_distance = data[row,0] - data[column,0]
                y_distance = data[row,1] - data[column,1]
                z_distance = data[row,2] - data[column,2]
                distance=np.sqrt(x_distance**2+y_distance**2+z_distance**2)

                if distance<=1.5 and row!=column: #We avoid printing values that are not really bond (too far away, >1.5) and distances between same atoms (=0)
                    outfile.write(F'{headers[row]} to {headers[column]}: {distance:.3f}\n')
